/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dicdemo;

import com.sun.speech.freetts.*;
import java.awt.Color;
import java.io.*;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.scene.text.Font.font;
import static javafx.scene.text.Font.font;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import javax.swing.Timer;

/**
 *
 * @author Dell
 */
public class UserFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserFrame
     */
    
    String[] str={""};
    String[] str1={"kkk"};
    private int t;
    private int n;
    Word dic;
    public UserFrame() {
        initComponents();
        dic = new Word();
        t=-1;
        n=-1;
        del.setVisible(false);
        pane1.setEditable(false);
        pane1.setContentType("text/html");
        jTextPane1.setContentType("text/html");
        jTextPane1.setEditable(false);
        jLabel2.setForeground(Color.BLUE);
        text1.setText("Cannot write");
        text1.setEditable(false);
        jTextPane1.setBackground(Color.red);
        jTextPane1.setText("<span style=\"color: red\">Please choose language that need to translate!</span>");
        jList1.setListData(str);
        jList1.setVisible(true);
        this.setSize(1064,840);
        this.setVisible(false);
        jLabel3.setText("");
        jLabel4.setVisible(false);
        dic.ReadFile_V_E();
        dic.ReadFile_E_V();
        //jFrame1.setJMenuBar(jMenuBar1);
        save.setVisible(false);
         String t0="Do Minh Kha";
          jLabel3.setForeground(Color.red);
          
           Timer t1;
            t1 = new Timer(80,  new ActionListener() {
            @Override
            
            public void actionPerformed(ActionEvent e) {
               if(jLabel3.getText().indexOf("D")==130||jLabel3.getText().indexOf("  ")!=0){
                 if(jLabel3.getText().indexOf("D")==130) jLabel3.setText("");
                 if(jLabel3.getText()=="") jLabel3.setText("e");
                 else if(jLabel3.getText()=="e") jLabel3.setText("he");
                 else if(jLabel3.getText()=="he") jLabel3.setText("ghe");
                 else if(jLabel3.getText()=="ghe") jLabel3.setText("Nghe");
                 else if(jLabel3.getText()=="Nghe") jLabel3.setText("g Nghe");
                 else if(jLabel3.getText()=="g Nghe") jLabel3.setText("ng Nghe");
                 else if(jLabel3.getText()=="ng Nghe") jLabel3.setText("ong Nghe");
                 else if(jLabel3.getText()=="ong Nghe") jLabel3.setText("Cong Nghe");
                  else if(jLabel3.getText()=="Cong Nghe") jLabel3.setText("c Cong Nghe");
                  else if(jLabel3.getText()=="c Cong Nghe") jLabel3.setText("oc Cong Nghe");
                  else if(jLabel3.getText()=="oc Cong Nghe") jLabel3.setText("hoc Cong Nghe");
                  else if(jLabel3.getText()=="hoc Cong Nghe") jLabel3.setText("i hoc Cong Nghe");
                  else if(jLabel3.getText()=="i hoc Cong Nghe") jLabel3.setText("ai hoc Cong Nghe");
                 else if(jLabel3.getText()=="ai hoc Cong Nghe") jLabel3.setText("  Dai hoc Cong Nghe");
                 
               }
                else jLabel3.setText("  "+jLabel3.getText());
              
              //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            
        });  
           t1.start();  
        //  }
          
        this.setLocationRelativeTo(null);
        
     //   this.setResizable(false);
       // MakeList();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search = new javax.swing.JButton();
        text1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        pane1 = new javax.swing.JTextPane();
        E_V = new javax.swing.JButton();
        V_E = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        home = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        del = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        addToFile = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        menu_E_V = new javax.swing.JMenuItem();
        menu_V_E = new javax.swing.JMenuItem();
        delWord = new javax.swing.JMenu();
        delWord_E = new javax.swing.JMenuItem();
        delWord_V = new javax.swing.JMenuItem();
        modify = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dictionary");
        setForeground(new java.awt.Color(153, 255, 51));

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        text1.setText("jTextField1");
        text1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text1MouseClicked(evt);
            }
        });
        text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text1ActionPerformed(evt);
            }
        });
        text1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text1KeyReleased(evt);
            }
        });

        pane1.setBackground(new java.awt.Color(102, 255, 255));
        pane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pane1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(pane1);

        E_V.setText("English-Vietnamses");
        E_V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_VActionPerformed(evt);
            }
        });

        V_E.setText("Vietnamese-EngLish");
        V_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V_EActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jScrollPane3.setViewportView(jTextPane1);

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("UET_Dictionary");
        jLabel2.setToolTipText("");
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(102, 255, 255));
        jLabel3.setFont(new java.awt.Font("Wide Latin", 3, 18)); // NOI18N
        jLabel3.setOpaque(true);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList1);

        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel4.setText("Thêm từ mới : English-Vietnam");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\NetBeansProjects\\DicDemo\\src\\dicdemo\\images.png")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        del.setText("Xoá");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        jMenu3.setText("File");

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exit.setText("exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu3.add(exit);

        addToFile.setText("Add to File");
        addToFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToFileActionPerformed(evt);
            }
        });
        jMenu3.add(addToFile);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");

        jMenu1.setText("addWord");

        menu_E_V.setText("EngLish-VietNam");
        menu_E_V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_E_VActionPerformed(evt);
            }
        });
        jMenu1.add(menu_E_V);

        menu_V_E.setText("VietNam-English");
        menu_V_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_V_EActionPerformed(evt);
            }
        });
        jMenu1.add(menu_V_E);

        jMenu4.add(jMenu1);

        delWord.setText("Delete Word");

        delWord_E.setText("English");
        delWord_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delWord_EActionPerformed(evt);
            }
        });
        delWord.add(delWord_E);

        delWord_V.setText("VietNam");
        delWord_V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delWord_VActionPerformed(evt);
            }
        });
        delWord.add(delWord_V);

        jMenu4.add(delWord);

        modify.setText("modify");
        jMenu4.add(modify);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(del)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(E_V, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153)
                        .addComponent(V_E, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(save)))
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(E_V)
                            .addComponent(V_E)
                            .addComponent(home))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(search))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(del)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(save)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(84, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(51, 51, 51))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        if(t!=-1){
            String a = jList1.getSelectedValue().toString();
       if(t==1){
          // dic.ReadFile_V_E();
            pane1.setText(dic.getDic_V_E(a));
       }
       if(t==0){
           // dic.ReadFile_E_V();
            pane1.setText(dic.getDic_E_V(a));
       }
        }
       text1.setText(jList1.getSelectedValue().toString());
        
    }//GEN-LAST:event_searchActionPerformed

    private void text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text1ActionPerformed
        // TODO add your handling code here:
        String a = text1.getText();
        a=a.toLowerCase();
        Word dic = new Word();
        String[] list = null ;
        if(t==0) {
          //  dic.ReadFile_E_V();
            list = dic.getList_E_V(a);
        }
        if(t==1) {
         //   dic.ReadFile_V_E();
            list = dic.getList_V_E(a);
        }
        jList1.setListData(list);
        
    }//GEN-LAST:event_text1ActionPerformed

    private void text1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text1KeyReleased
        // TODO add your handling code here:
        if(t==0||n==0){
            explain_E_V();
        }
        if(t==1||n==1){
            explain_V_E();
        }
    }//GEN-LAST:event_text1KeyReleased

    private void E_VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_VActionPerformed
        // TODO add your handling code here:
      //  if(t!=-1)  explain_E_V();
        if(t==-1) text1.setText("");
        t=0;
        text1.setEditable(true);
        jTextPane1.setText("<span style=\"color: blue\">From: <i> English </i> to <i> VietNam </i></span>");
        String a = text1.getText();
        a=a.toLowerCase();
        String[] list ;
       // dic.ReadFile_E_V();
        list = dic.getList_E_V(a);
        jList1.setListData(list);
    }//GEN-LAST:event_E_VActionPerformed

    private void V_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V_EActionPerformed
        // TODO add your handling code here:
    //    if(t!=-1)   explain_V_E();
        if(t==-1) text1.setText("");
        t=1;
        text1.setEditable(true);
       // text1.setText("");
      
        jTextPane1.setText("<span style=\"color: blue\">From: <i> VietNam </i> to <i> English </i></span>");
        String a = text1.getText();
        a=a.toLowerCase();
        String[] list ;
    //    dic.ReadFile_V_E();
        list = dic.getList_V_E(a);
        jList1.setListData(list);
    }//GEN-LAST:event_V_EActionPerformed

    private void text1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text1MouseClicked
        // TODO add your handling code here:
        if(t==1||t==0){
        text1.setText("");
        jList1.setListData(str);
        }
        if(n!=-1){
            text1.setText("");
            jList1.setListData(str);
        }
    }//GEN-LAST:event_text1MouseClicked

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void menu_E_VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_E_VActionPerformed
        // TODO add your handling code here:
        n=0;
        del.setVisible(false);
         jTextPane1.setContentType("text");
        jLabel4.setVisible(true);
        jLabel4.setText("Thêm từ mới: From English to VietNam");
        search.setVisible(false);
        E_V.setVisible(false);
        V_E.setVisible(false);
        save.setVisible(true);
        jTextPane1.setText("Nhập từ cần thêm tại đây:  ");
        jTextPane1.setEditable(true);
        pane1.setText("Nhập nghĩa của từ tại đây: ");
        pane1.setEditable(true);
        jList1.setVisible(false);
        text1.setVisible(false);
    }//GEN-LAST:event_menu_E_VActionPerformed

    private void menu_V_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_V_EActionPerformed
        // TODO add your handling code here:
        n=1;
         jTextPane1.setContentType("text");
         del.setVisible(false);
        jLabel4.setVisible(true);
        jLabel4.setText("Thêm từ mới: From VietNam to English");
        search.setVisible(false);
        E_V.setVisible(false);
        V_E.setVisible(false);
        save.setVisible(true);
        jTextPane1.setText("Nhập từ cần thêm tại đây:  ");
        jTextPane1.setEditable(true);
        pane1.setText("Nhập nghĩa của từ tại đây: ");
        pane1.setEditable(true);
        jList1.setVisible(false);
        text1.setVisible(false);
    }//GEN-LAST:event_menu_V_EActionPerformed

    private void pane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pane1MouseClicked
        // TODO add your handling code here:
        if(n!=-1){
            pane1.setText("");
        }
    }//GEN-LAST:event_pane1MouseClicked
 
    public static final String VoiceName="kevin16";
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        Voice voice;
        VoiceManager vm = VoiceManager.getInstance();
        voice = vm.getVoice(VoiceName);
        voice.allocate();
        try{
            voice.speak(jList1.getSelectedValue());
            
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        n=-1;
        t=-1;
        
        del.setVisible(false);
        jTextPane1.setContentType("text/html");
        search.setVisible(true);
        search.setText("Search");
        E_V.setVisible(true);
        V_E.setVisible(true);
        save.setVisible(false);
        jTextPane1.setVisible(true);
        jTextPane1.setEditable(false);
        pane1.setEditable(false);
        pane1.setText("");
        jLabel4.setVisible(false);
        pane1.setEditable(false);
        pane1.setContentType("text/html");
        pane1.setText("");
        jLabel2.setForeground(Color.BLUE);
        text1.setText("Cannot write");
        text1.setEditable(false);
        text1.setVisible(true);
        jTextPane1.setBackground(Color.red);
        jTextPane1.setText("<span style=\"color: red\">Please choose language that need to translate!</span>");
        jList1.setListData(str);
        jList1.setVisible(true);
        jLabel3.setText("");
        jLabel4.setVisible(false);
        save.setVisible(false);
    }//GEN-LAST:event_homeActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
     //   jTextPane1.setContentType("text");
        if(n!=-1){
            String a = jTextPane1.getText();
            String b = pane1.getText();
            dic.addWord(a, b, n);
        }
        JOptionPane.showMessageDialog(rootPane,"Lưu thành công","UET_DIC", HEIGHT);
    }//GEN-LAST:event_saveActionPerformed

    private void addToFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToFileActionPerformed
        // TODO add your handling code here:
        String a = text1.getText();
        if(t==-1){
            JOptionPane.showMessageDialog(rootPane,"Cannot add to file!\n Please choose language!", a, HEIGHT);
        }
        else if(t!=-1){
          try {
            int h = dic.releaseFile(a, t);
            if(h==0){
                JOptionPane.showMessageDialog(rootPane,"Please type word","UET_DIC",JOptionPane.ERROR);
               // JOptionPane.showMessageDialog(rootPane,"Please type word",JOptionPane.ERROR);
            }
         } catch (IOException ex) {
            Logger.getLogger(UserFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
            JOptionPane.showMessageDialog(rootPane,"Add to file successfully!","Success",JOptionPane.PLAIN_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_addToFileActionPerformed

    private void delWord_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delWord_EActionPerformed
        // TODO add your handling code here:
        n=0;
        del.setVisible(true);
        jLabel4.setVisible(false);
        search.setVisible(false);
        E_V.setVisible(false);
        V_E.setVisible(false);
        save.setVisible(false);
        jTextPane1.setVisible(true);
        jTextPane1.setContentType("text/html");
         jTextPane1.setEditable(false);
        jTextPane1.setText("<span style=\"color: blue\"> Xoá từ Tiếng Anh</span>");
        pane1.setEditable(false);
        pane1.setText("");
       
        jList1.setVisible(true);
        jList1.setListData(str);
        text1.setVisible(true);
        text1.setText("Nhập từ cần xoá tại đây");
        text1.setEditable(true);
        
    }//GEN-LAST:event_delWord_EActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        String a = text1.getText();
      //  a=jList1.getSelectedValue().toString();
        System.out.println(a+"1");
        int k = JOptionPane.showConfirmDialog(rootPane,"Bạn có chắc chắn xoá không?");
        if(k==0){
            int h = dic.delWord(a, n);
            if(h==0){
                pane1.setContentType("text/html");
                pane1.setText("<span style=\"color: red\">----------- TỪ NÀY KHÔNG TỒN TẠI ----------</span>");
               // JOptionPane.showMessageDialog(rootPane,"Please type word","UET_DIC",JOptionPane.ERROR);
                // JOptionPane.showMessageDialog(rootPane,"Please type word",JOptionPane.ERROR);
            }
            else {
                pane1.setContentType("text/html");
                pane1.setText("<span style=\"color: blue\">----------- XOÁ TỪ THÀNH CÔNG ----------</span>");
               
            }
            text1.setText("");
            jList1.setListData(str);
        }
    }//GEN-LAST:event_delActionPerformed

    private void delWord_VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delWord_VActionPerformed
        // TODO add your handling code here:
         n=1;
         del.setVisible(true);
        jLabel4.setVisible(false);
        search.setVisible(false);
        E_V.setVisible(false);
        V_E.setVisible(false);
        save.setVisible(false);
        jTextPane1.setVisible(true);
        jTextPane1.setContentType("text/html");
        jTextPane1.setText("<span style=\"color: blue\"> Xoá từ Tiếng Việt</span>");
        jTextPane1.setEditable(false);
        pane1.setText("");
        pane1.setEditable(false);
        jList1.setVisible(true);
        jList1.setListData(str);
        text1.setVisible(true);
        text1.setText("Nhập từ cần xoá tại đây");
        text1.setEditable(true);
    }//GEN-LAST:event_delWord_VActionPerformed
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserFrame().setVisible(true);
            }
        });
    }
    public void explain_V_E(){
        String a = text1.getText();
        a=a.toLowerCase();
        String[] list ;
        list = dic.getList_V_E(a);
        jList1.setListData(list);
    }
    public void explain_E_V(){
        String a = text1.getText();
        a=a.toLowerCase();
        String[] list;
      //  dic.ReadFile_E_V();
        list = dic.getList_E_V(a);
        jList1.setListData(list);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton E_V;
    private javax.swing.JButton V_E;
    private javax.swing.JMenuItem addToFile;
    private javax.swing.JButton del;
    private javax.swing.JMenu delWord;
    private javax.swing.JMenuItem delWord_E;
    private javax.swing.JMenuItem delWord_V;
    private javax.swing.JMenuItem exit;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JMenuItem menu_E_V;
    private javax.swing.JMenuItem menu_V_E;
    private javax.swing.JMenuItem modify;
    private javax.swing.JTextPane pane1;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JTextField text1;
    // End of variables declaration//GEN-END:variables
}
